### ISSUE TITLE
Some security pointers

### ISSUE THREAD

**Issue by jesperordrup** [arrowban/sveltekit-pocketbase-turborepo-template#2]
Thanks for sharing!! 

I can see that you have ensured that the logged in user can only update own content. But how do ensure that they dont mess with own data. When you put the update logic on the client then the user can alter anything before updating. For instance in this example I can change the count to 200 in one go. 

In this scenario it doesnt matter much but its worth mentioning so this doesnt become "the way" to update.

IMHO any mutations should be done via serverside logic.

**Comment by arrowban** [comment]
@jesperordrup Thanks for raising this security concern!

You're right. The way the template is set up, a bad actor could take their auth token and send an API request to the Pocketbase server updating the count on their post to whatever they want

Moving mutations to the server would make it a little more difficult to abuse the API like this, but not impossible. If we also required admin privileges for every database mutation, that would address the issue
 
I don't personally prefer that approach since it requires writing a lot more code, as every mutation in your app would require a new API endpoint with it's own validation logic

Instead, I personally prefer updating API rules to only support the intended operations when possible. In this case, unfortunately I don't think it's possible to use API rules because addition/subtraction is not supported (`user = @request.auth.id && @request.data.count:isset = true && count = @request.data.count - 1` would be the update rule to use, but it is not supported)

I won't update the template to increment count with an API endpoint because like you said, it doesn't matter in this example, but thanks again for raising this issue!

Note: Without rate limiting neither approach would do a thorough job of preventing abuse, I will probably add rate limiting to this template for myself soon enough, but hopefully built-in rate limiting for Pocketbase is coming soon https://github.com/pocketbase/pocketbase/issues/1232
